version: "3"
services:
  database:
    image: openjdk:11
    entrypoint: [ "java", "-jar", "./build/libs/aria.jar" ]
    working_dir: "/usr/src/aria-database"
    volumes:
      - ./build:/usr/src/aria-database/build:ro
      - ./config:/usr/src/aria-database/config:ro
    ports:
      - 8080:8080
  database-postgres:
    image: postgres:10
    environment: 
      POSTGRES_DB: ariadb
      POSTGRES_USER: aria
      POSTGRES:PASSWORD: music
