version: "3"
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: ariadb
      POSTGRES_USER: aria
      POSTGRES_PASSWORD: music
    restart: always
  dbapp:
    build: .
    image: aria-database:latest
    volumes:
    - ./config:/usr/src/aria-database/config
    restart: on-failure:3
