DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS playlist_entry;
DROP TABLE IF EXISTS aria_user;
DROP TABLE IF EXISTS aria_group;
DROP TABLE IF EXISTS group_member;
DROP TABLE IF EXISTS entry;
DROP TABLE IF EXISTS gpm_meta;
