name: dispatch
on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            github.repos.createDispatchEvent({
              owner: 'aria-music',
              repo: 'core-deploy',
              event_type: 'aria-database update'
            })
